export const CREATE_AUTHOR_ERROR = 'CREATE_AUTHOR_ERROR';
export const CREATE_AUTHOR_SUCCESS = 'CREATE_AUTHOR_SUCCESS';

export const DELETE_AUTHOR_ERROR = 'DELETE_AUTHOR_ERROR';
export const DELETE_AUTHOR_SUCCESS = 'DELETE_AUTHOR_SUCCESS';

export const UNDELETE_AUTHOR_ERROR = 'UNDELETE_AUTHOR_ERROR';

export const UPDATE_AUTHOR_ERROR = 'UPDATE_AUTHOR_ERROR';
export const UPDATE_AUTHOR_SUCCESS = 'UPDATE_AUTHOR_SUCCESS';

export const FILTER_AUTHORS = 'FILTER_AUTHORS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const UNLOAD_AUTHORS_SUCCESS = 'UNLOAD_AUTHORS_SUCCESS';
