export const CREATE_LOCATION_ERROR = 'CREATE_LOCATION_ERROR';
export const CREATE_LOCATION_SUCCESS = 'CREATE_LOCATION_SUCCESS';

export const DELETE_LOCATION_ERROR = 'DELETE_LOCATION_ERROR';
export const DELETE_LOCATION_SUCCESS = 'DELETE_LOCATION_SUCCESS';

export const UNDELETE_LOCATION_ERROR = 'UNDELETE_LOCATION_ERROR';

export const UPDATE_LOCATION_ERROR = 'UPDATE_LOCATION_ERROR';
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_SUCCESS';

export const FILTER_LOCATIONS = 'FILTER_LOCATIONS';
export const LOAD_LOCATIONS_SUCCESS = 'LOAD_LOCATIONS_SUCCESS';
export const UNLOAD_LOCATIONS_SUCCESS = 'UNLOAD_LOCATIONS_SUCCESS';
