export const CREATE_SERIE_ERROR = 'CREATE_SERIE_ERROR';
export const CREATE_SERIE_SUCCESS = 'CREATE_SERIE_SUCCESS';

export const DELETE_SERIE_ERROR = 'DELETE_SERIE_ERROR';
export const DELETE_SERIE_SUCCESS = 'DELETE_SERIE_SUCCESS';

export const UNDELETE_SERIE_ERROR = 'UNDELETE_SERIE_ERROR';

export const UPDATE_SERIE_ERROR = 'UPDATE_SERIE_ERROR';
export const UPDATE_SERIE_SUCCESS = 'UPDATE_SERIE_SUCCESS';

export const FILTER_SERIES = 'FILTER_SERIES';
export const LOAD_SERIES_SUCCESS = 'LOAD_SERIES_SUCCESS';
export const UNLOAD_SERIES_SUCCESS = 'UNLOAD_SERIES_SUCCESS';
