export const CREATE_ARTIST_ERROR = 'CREATE_ARTIST_ERROR';
export const CREATE_ARTIST_SUCCESS = 'CREATE_ARTIST_SUCCESS';

export const DELETE_ARTIST_ERROR = 'DELETE_ARTIST_ERROR';
export const DELETE_ARTIST_SUCCESS = 'DELETE_ARTIST_SUCCESS';

export const UNDELETE_ARTIST_ERROR = 'UNDELETE_ARTIST_ERROR';

export const UPDATE_ARTIST_ERROR = 'UPDATE_ARTIST_ERROR';
export const UPDATE_ARTIST_SUCCESS = 'UPDATE_ARTIST_SUCCESS';

export const FILTER_ARTISTS = 'FILTER_ARTISTS';
export const LOAD_ARTISTS_SUCCESS = 'LOAD_ARTISTS_SUCCESS';
export const UNLOAD_ARTISTS_SUCCESS = 'UNLOAD_ARTISTS_SUCCESS';
