export const CREATE_BOOK_ERROR = 'CREATE_BOOK_ERROR';
export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';

export const SELECT_BOOK = 'SELECT_BOOK';
export const UNSELECT_BOOK = 'UNSELECT_BOOK';

export const LOAD_BOOK = 'LOAD_BOOK';

export const DELETE_BOOK_ERROR = 'DELETE_BOOK_ERROR';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';

export const UNDELETE_BOOK_ERROR = 'UNDELETE_BOOK_ERROR';

export const UPDATE_BOOK_ERROR = 'UPDATE_BOOK_ERROR';
export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';

export const FILTER_BOOKS = 'FILTER_BOOKS';
export const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';
export const UNLOAD_BOOKS_SUCCESS = 'UNLOAD_BOOKS_SUCCESS';
