export const CREATE_COLLECTION_ERROR = 'CREATE_COLLECTION_ERROR';
export const CREATE_COLLECTION_SUCCESS = 'CREATE_COLLECTION_SUCCESS';

export const DELETE_COLLECTION_ERROR = 'DELETE_COLLECTION_ERROR';
export const DELETE_COLLECTION_SUCCESS = 'DELETE_COLLECTION_SUCCESS';

export const UNDELETE_COLLECTION_ERROR = 'UNDELETE_COLLECTION_ERROR';

export const UPDATE_COLLECTION_ERROR = 'UPDATE_COLLECTION_ERROR';
export const UPDATE_COLLECTION_SUCCESS = 'UPDATE_COLLECTION_SUCCESS';

export const FILTER_COLLECTIONS = 'FILTER_COLLECTIONS';
export const LOAD_COLLECTIONS_SUCCESS = 'LOAD_COLLECTIONS_SUCCESS';
export const UNLOAD_COLLECTIONS_SUCCESS = 'UNLOAD_COLLECTIONS_SUCCESS';
