export const CREATE_EDITOR_ERROR = 'CREATE_EDITOR_ERROR';
export const CREATE_EDITOR_SUCCESS = 'CREATE_EDITOR_SUCCESS';

export const DELETE_EDITOR_ERROR = 'DELETE_EDITOR_ERROR';
export const DELETE_EDITOR_SUCCESS = 'DELETE_EDITOR_SUCCESS';

export const UNDELETE_EDITOR_ERROR = 'UNDELETE_EDITOR_ERROR';

export const UPDATE_EDITOR_ERROR = 'UPDATE_EDITOR_ERROR';
export const UPDATE_EDITOR_SUCCESS = 'UPDATE_EDITOR_SUCCESS';

export const FILTER_EDITORS = 'FILTER_EDITORS';
export const LOAD_EDITORS_SUCCESS = 'LOAD_EDITORS_SUCCESS';
export const UNLOAD_EDITORS_SUCCESS = 'UNLOAD_EDITORS_SUCCESS';
