export const CREATE_STYLE_ERROR = 'CREATE_STYLE_ERROR';
export const CREATE_STYLE_SUCCESS = 'CREATE_STYLE_SUCCESS';

export const DELETE_STYLE_ERROR = 'DELETE_STYLE_ERROR';
export const DELETE_STYLE_SUCCESS = 'DELETE_STYLE_SUCCESS';

export const UNDELETE_STYLE_ERROR = 'UNDELETE_STYLE_ERROR';

export const UPDATE_STYLE_ERROR = 'UPDATE_STYLE_ERROR';
export const UPDATE_STYLE_SUCCESS = 'UPDATE_STYLE_SUCCESS';

export const FILTER_STYLES = 'FILTER_STYLES';
export const LOAD_STYLES_SUCCESS = 'LOAD_STYLES_SUCCESS';
export const UNLOAD_STYLES_SUCCESS = 'UNLOAD_STYLES_SUCCESS';
